name: call-reusable-workflow
on: push

jobs:
  call-resusableSaptarshi:
    uses: Saptarshi666/github-actions-basic-to-advance/.github/workflows/mj.yml@main
  call-reusable-workflow:
    uses: bgerelmaa/github-actions-basic-to-advance/.github/workflows/reusable-workflow.yaml@main
 