name: Call Reusable CI Workflow

on:
  push:
    branches:
      - main

jobs:
    call-workflow-gemma:
        uses: bgerelmaa/github-actions-basic-to-advance/.github/workflows/reusable-workflow.yaml@main
    call-workflow-saptarshi:
        uses: Saptarshi666/github-actions-basic-to-advance/.github/workflows/reusable-simple.yaml@main